# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='book_name',
        ),
        migrations.AddField(
            model_name='author',
            name='book_name',
            field=models.ManyToManyField(to='book.Books'),
        ),
    ]
