# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-21 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20160719_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='book_name',
        ),
        migrations.AddField(
            model_name='books',
            name='author_name',
            field=models.ManyToManyField(to='book.Author'),
        ),
    ]
